name: Dependency Review

on:

permissions:
  contents: read
  security-events: write # Required for uploads to GHAS

jobs:
  build:
    uses: ./.github/workflows/build.yml

  dependency:
    name: Review
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:  ['1.26']

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Artifact
      uses: actions/download-artifact@v8
      with:
        name: build
        path: submodule
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v5
