name: Dependency Review

on:
  workflow_dispatch:
    inputs:
      base_ref:
        type: string
      head_ref:
        type: string
  workflow_call:
    inputs:
      base_ref:
        type: string
      head_ref:
        type: string

permissions:
  contents: read
  security-events: write # Required for uploads to GHAS

jobs:
  build:
    uses: ./.github/workflows/build.yml

  dependency:
    name: Review
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Artifact
      uses: actions/download-artifact@v8
      with:
        name: build
        path: submodule
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v5
      with:
        base_ref: ${{ inputs.base_ref || github.base_ref }}
        head_ref: ${{ inputs.head_ref || github.head_ref }}
